### PR TITLE
Add Fontawesome 5 to use for icons

### PR DESCRIPTION
**Pull request by rickard-von-essen**
See https://fontawesome.com/

Example:
- SDcard icon in the top bar
- GitHub icon in the footer link

[Screenshot 2020-06-27 at 21 16 57](https://user-images.githubusercontent.com/557699/85930334-bbf4d000-b8bb-11ea-8bc7-52ee67cf7954.png)

### CODE REVIEW

**Comment by alvieboy** [comment]
There's only a minor issue: spiffs (where the files will be stored inside the chip) does not support directories. So either I change this to my own storage or we need to remove the directories altogether. Let me think a bit about it - do not change the request yet.

**Comment by rickard-von-essen** [comment]
Ok. I thought about a similar issue, is there any sizing constraints for the  SPIFFS?

It should be fairly easy to mangle the paths to be flat. Alse we could use svg's instead of the web fonts and only add exactly the icons we use. It might be good to reduce size if needed.

**Comment by alvieboy** [comment]
There is a 32-byte filename size constraint. Asides from that I think if you keep file sizes <2GB you should be ok.
Remember we can "gz" compress any static file, I do believe all browsers support the gzip transfer-encoding.

**Comment by rickard-von-essen** [comment]
Closing this for now since I'm going ahead with the Angular web UI instead.

**Pull request closed without merging**
